version: 0.2

phases:
  install:
    commands:
      - cd infra/cdk
      - npm install -g npm
      - npm install -g aws-cdk
      - npm ci
  build:
    commands:
      - npm run build
      - npm run synth-infra
      - pwd
      - ls build/*
      - cd build
      - ls
      - pwd

artifacts:
  files:
    - infra/cdk/build/*
  discard-paths: yes